window.__ModuleLoader__.load({
  id: "dsh-uni-browser",
  factory: (require) => {
    const module = { exports: {} }; const exports = module.exports; const React = require("react"); const h = React.createElement; const inject = ["slots", "connection"];
    function apply(ctx) {
      const call = async (endpoint, args = {}) => { const response = await ctx.connection.rpc.call("/dsh-uni-browser", endpoint, { args }); if (!response?.ok) throw new Error(response?.error?.message ?? "Browser request failed"); return response.value; };
      function BrowserSettings() {
        const [profiles, setProfiles] = React.useState([]); const [health, setHealth] = React.useState(null); const [name, setName] = React.useState(""); const [engine, setEngine] = React.useState("chromium"); const [error, setError] = React.useState(""); const [working, setWorking] = React.useState(false);
        const refresh = React.useCallback(async () => { const [profileResult, healthResult] = await Promise.all([call("profiles"), call("health").catch(() => null)]); setProfiles(profileResult.profiles ?? []); setHealth(healthResult); setError(""); }, []);
        React.useEffect(() => { void refresh().catch((cause) => setError(String(cause.message ?? cause))); }, [refresh]);
        const create = async (event) => { event.preventDefault(); if (!name.trim() || working) return; setWorking(true); try { await call("create", { name: name.trim(), engine, headless: false }); setName(""); await refresh(); } catch (cause) { setError(String(cause.message ?? cause)); } finally { setWorking(false); } };
        const operate = async (endpoint, id, confirm = undefined) => { setWorking(true); try { await call(endpoint, { id, ...(confirm === undefined ? {} : { confirm }) }); await refresh(); } catch (cause) { setError(String(cause.message ?? cause)); } finally { setWorking(false); } };
        const field = { boxSizing: "border-box", minHeight: 38, border: "1px solid var(--dsw-alias-border-l2, #ddd)", borderRadius: 9, padding: "0 11px", background: "var(--dsw-alias-bg-layer-1, #fff)", color: "inherit" }; const button = { ...field, cursor: "pointer" };
        return h("div", { style: { width: "min(720px, 100%)", padding: "8px 4px 48px" } }, h("div", { style: { marginBottom: 26 } }, h("h2", { style: { margin: "0 0 6px", fontSize: 22 } }, "Uni Browser"), h("p", { style: { margin: 0, color: "var(--dsw-alias-text-secondary, #777)", lineHeight: 1.5 } }, "Named browser profiles keep their local login state. DSH never displays passwords, cookies, or daemon tokens.")), error && h("p", { role: "alert", style: { padding: 10, borderRadius: 9, background: "rgba(210,48,48,.08)", color: "var(--dsw-alias-state-error-primary, #b42318)" } }, error), h("section", { style: { marginBottom: 28 } }, h("h3", { style: { margin: "0 0 6px", fontSize: 15 } }, "Local daemon"), h("p", { style: { margin: 0, color: health?.online ? "#228b5b" : "var(--dsw-alias-text-secondary, #777)", fontSize: 13 } }, health?.online ? `Online · ${health.socketPath}` : "Offline · DSH will start the packaged runtime when needed.")), h("section", { style: { marginBottom: 28 } }, h("h3", { style: { margin: "0 0 8px", fontSize: 15 } }, "New persistent profile"), h("form", { onSubmit: create, style: { display: "flex", gap: 8, flexWrap: "wrap" } }, h("input", { value: name, onChange: (event) => setName(event.target.value), placeholder: "e.g. Research", style: { ...field, flex: "1 1 240px" } }), h("select", { value: engine, onChange: (event) => setEngine(event.target.value), style: button }, h("option", { value: "chromium" }, "Chromium"), h("option", { value: "camoufox" }, "Camoufox")), h("button", { type: "submit", disabled: working || !name.trim(), style: button }, "Create"))), h("section", null, h("h3", { style: { margin: "0 0 10px", fontSize: 15 } }, "Registered profiles"), h("div", { style: { display: "grid", gap: 8 } }, profiles.map((profile) => h("div", { key: profile.id, style: { padding: "12px", borderRadius: 10, background: "var(--dsw-alias-bg-layer-2, #f6f7f8)" } }, h("div", { style: { display: "flex", justifyContent: "space-between", gap: 12 } }, h("div", null, h("strong", null, profile.name), h("div", { style: { color: "var(--dsw-alias-text-secondary, #777)", fontSize: 12, marginTop: 3 } }, `${profile.engine} · ${profile.active ? "Running" : "Stopped"}`)), h("div", { style: { display: "flex", gap: 6 } }, h("button", { type: "button", disabled: working, onClick: () => operate(profile.active ? "close" : "open", profile.id), style: button }, profile.active ? "Stop" : "Open"), h("button", { type: "button", disabled: working, onClick: () => { if (window.confirm(`Forget ${profile.name}? Its local login state will be deleted.`)) void operate("forget", profile.id, true); }, style: { ...button, color: "var(--dsw-alias-state-error-primary, #b42318)" } }, "Forget"))))), profiles.length === 0 && h("p", { style: { color: "var(--dsw-alias-text-secondary, #777)", fontSize: 13 } }, "No profiles registered yet."))));
      }
      ctx.slots.inject("settings.section", () => ctx.slots.register({ name: "settings.section", id: "uni-browser", order: 36, label: () => "Uni Browser" }, BrowserSettings));
    }
    exports.apply = apply; exports.inject = inject; return module.exports;
  }
});
